### ISSUE TITLE
Failed to enable SSP

### ISSUE THREAD

**Issue by aliabdullahnasiri** [palacita135/BlueDucky#1]
# Failed to enable SSP
I encounter a ConnectionFailureException error when running the BlueDucky.py script.
```
2024-10-01 20:03:30,151 - ERROR - Failed to enable SSP: Can't set Simple Pairing mode on hci0: Input/output error (5)

2024-10-01 20:03:30,151 - ERROR - Error enabling SSP: Failed to enable SSP
Traceback (most recent call last):
  File "/home/aliabdullah/BlueDucky/BlueDucky.py", line 755, in <module>
    main()
  File "/home/aliabdullah/BlueDucky/BlueDucky.py", line 720, in main
    adapter.enable_ssp()
  File "/home/aliabdullah/BlueDucky/BlueDucky.py", line 111, in enable_ssp
    raise ConnectionFailureException("Failed to enable SSP")
ConnectionFailureException: Failed to enable SSP
```
How can I solve this problem?

**Comment by palacita135** [comment]
sudo systemctl status bluetooth
sudo systemctl restart bluetooth

sudo hciconfig hci0 down
sudo hciconfig hci0 up

Check the Bluetooth service status.
Ensure proper permissions for the Bluetooth device.
Try resetting the Bluetooth adapter.
Make sure the system is up-to-date with the latest drivers.
Check if other software is conflicting with the Bluetooth device.
Verify the Bluetooth adapter supports SSP.
Add more logging for debugging in the code.
